name: Actualizar Feature Flag

on:
  push:
    branches:
      - main

jobs:
  update-feature-flag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Activar la versión 2.0 mejorada
      run: |
        curl -X PATCH \
          "https://app.launchdarkly.com/api/v2/flags/default/version-2.0-mejorada" \
          -H "Authorization: Bearer ${{ secrets.LAUNCHDARKLY_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{
                "patch": [
                  {
                    "op": "replace",
                    "path": "/environments/production/on",
                    "value": true
                  }
                ]
              }'
