name: Actualizar Feature Flag

on:
  push:
    branches:
      - main 

jobs:
  update-feature-flag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Activar/Desactivar la versión mejorada
      run: |
        # Determinar el valor del flag
        if [ "${{ github.event_name }}" == "push" ]; then
          flag_value="true"
        else
          flag_value="false"
        fi

        # Actualizar el feature flag en LaunchDarkly
        curl -X PATCH \
          "https://app.launchdarkly.com/api/v2/flags/default/version-mejorada" \
          -H "Authorization: Bearer ${{ secrets.LAUNCHDARKLY_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{
                "patch": [
                  {
                    "op": "replace",
                    "path": "/environments/production/on",
                    "value": '"$flag_value"'
                  }
                ]
              }'
